### ISSUE TITLE
Couple small touches in gui 

### ISSUE THREAD

**Issue by nazariev** [fracpete/jfilechooser-bookmarks#1]
Hi,

It will look slightly better, if you add background for each other row in directory listing:
Default, line  36:
    UIDefaults defaults = UIManager.getLookAndFeelDefaults();
    if (defaults.get("Table.alternateRowColor") == null)
      defaults.put("Table.alternateRowColor", new Color(240, 240, 240));

And group bookmark panel with additional border:
AbstractBookmarksPanel, line # 132:
    this.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

Andrei

**Comment by fracpete** [comment]
Thanks for the suggestions. Both changes can be easily applied in your own projects that use the library (and the `Default` class is just an example class), so I won't change anything. I'm not a big fan of alternating row colors and the bevel clashes visually with the way I'm integrating it in my other projects.
